# Generated by Django 5.2.17 on 2026-09-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('suffix', models.CharField(blank=True, choices=[('', 'VP'), ('_no_vp', 'no VP')], default='', max_length=10)),
                ('path', models.CharField(help_text='Relative to the repo root', max_length=500, unique=True)),
                ('is_latest', models.BooleanField(default=False, help_text='Newest file for this (area, suffix)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_variants', to='tracker.area')),
            ],
            options={
                'verbose_name': 'CV variant',
                'ordering': ['area__slug', '-date', 'suffix'],
            },
        ),
    ]
