# Generated by Django 5.2.17 on 2026-09-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('path', models.CharField(help_text='Relative to the repo root', max_length=500, unique=True)),
                ('is_functional', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'base CV',
                'verbose_name_plural': 'base CVs',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
