# Generated by Django 5.2.17 on 2026-09-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_basecv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CvVariant',
        ),
    ]
