"""Scaffold a new job-search data root and wire this checkout to it (plan §3.2).

Deliberately NON-interactive: every answer arrives as a flag. `/jobstudio init` is
the conversational half — it asks where the data should live and who the user is, then
calls this. Keeping the prompts in the skill and the mechanics here means there is one
code path, testable headlessly, and the smoke test can drive it.

Idempotent. Re-running against an existing data root adds what is missing and leaves
what is there alone; nothing is overwritten without --force. There is deliberately no
"wipe and recreate" mode — this runs against a directory holding someone's whole job
search, and a destructive flag would eventually be typed by accident.

    python src/jobsinit.py --data-root ~/jobstudio-data --from-example \
        --name "Alex Rivera" --email alex@example.com --location Bristol
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import config

REPO = config.REPO_ROOT
EXAMPLE = REPO / "example-data"

# The subdirectories of a data root. `init` creates them all, even the ones a given
# user may never fill, so the skill can write into any of them without checking first.
TREE = ["jobs/applications", "jobs/companies", "jobs/cv/base", "jobs/notes",
        "jobs/profile", "jobs/scans", "jobs/targets", "exports", "backups/django"]


def _say(msg: str) -> None:
    print(f"  {msg}")


def _write(path: Path, text: str, force: bool) -> bool:
    """Write unless it exists. Returns True if written."""
    if path.exists() and not force:
        _say(f"kept     {path}  (exists)")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    _say(f"wrote    {path}")
    return True


# ---------------------------------------------------------------------------
# the data root
# ---------------------------------------------------------------------------

def make_data_root(root: Path, from_example: bool, force: bool) -> None:
    root.mkdir(parents=True, exist_ok=True)
    for rel in TREE:
        (root / rel).mkdir(parents=True, exist_ok=True)
    _say(f"data root {root}")

    if not from_example:
        return

    # Copy rather than move: example-data/ stays read-only in the repo, so `init` is
    # re-runnable and the example can never be committed back with a user's edits in
    # it (plan §3.2, the deliberate deviation from "ship the example AS the data").
    for src in (EXAMPLE / "jobs").rglob("*"):
        if src.is_file():
            dest = root / "jobs" / src.relative_to(EXAMPLE / "jobs")
            if dest.exists() and not force:
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
    _say("copied   example jobs/ tree")


def write_config_yaml(root: Path, name: str, email: str, location: str, force: bool) -> None:
    slug = "-".join(name.lower().split())
    _write(root / "config.yaml", f"""# Identity for this job search (plan §3.4). Everything that needs your name,
# email or location reads it from here rather than having it baked into code.

identity:
  full_name: {name}
  slug: {slug}
  email: {email}
  location: {location}

site:
  footer_name: {name}
""", force)


# ---------------------------------------------------------------------------
# the four per-checkout files, plus the machine-level one
# ---------------------------------------------------------------------------

def wire_checkout(root: Path, venv_python: Path, force: bool) -> None:
    # 1. the pointer — per checkout, and it beats ~/.jobstudio.ini on purpose, so a
    #    second checkout (a sandbox) can point somewhere else without touching $HOME.
    _write(REPO / ".jobstudio-data", f"{root}\n", force)

    # 2. the venv wrapper (§3.3), so no script needs an absolute interpreter path
    py = REPO / "tools" / "py"
    if _write(py, f'#!/usr/bin/env bash\n# Generated by `jobstudio init`. Gitignored: the path is personal.\nexec "{venv_python}" "$@"\n', force):
        py.chmod(0o755)

    # 3. Claude Code's permissions — without this every session prompts on every file
    #    access outside the repo, which post-split is most of them (§5.4)
    settings = REPO / ".claude" / "settings.local.json"
    data = {}
    if settings.is_file():
        try:
            data = json.loads(settings.read_text())
        except json.JSONDecodeError:
            _say(f"WARNING  {settings} is not valid JSON — leaving it alone")
            data = None
    if data is not None:
        dirs = data.setdefault("permissions", {}).setdefault("additionalDirectories", [])
        if str(root) not in dirs:
            dirs.append(str(root))
            settings.parent.mkdir(parents=True, exist_ok=True)
            settings.write_text(json.dumps(data, indent=2) + "\n")
            _say(f"wrote    {settings}  (data root added to additionalDirectories)")
        else:
            _say(f"kept     {settings}  (already lists the data root)")

    # 4. one VS Code window over two folders, so the code/data boundary stays visible
    #    in Source Control rather than being something to remember (§5.4)
    _write(REPO / "jobstudio.code-workspace", json.dumps({
        "folders": [{"path": str(REPO), "name": "toolkit (code)"},
                    {"path": str(root), "name": "my job search (data)"}],
        "settings": {},
    }, indent=2) + "\n", force)

    # 5. Django's local settings, if this is a fresh clone
    ls = REPO / "src" / "web" / "local_settings.py"
    if not ls.is_file():
        shutil.copy2(REPO / "src" / "web" / "local_settings_example.py", ls)
        _say(f"wrote    {ls}  (from local_settings_example.py)")
    else:
        _say(f"kept     {ls}  (exists)")


def write_global_settings(root: Path, force: bool) -> None:
    """~/.jobstudio.ini (§3.6) — the layer that works when cwd is not the repo.

    Writing into $HOME is more invasive than writing inside the project, so this never
    overwrites silently: an existing file is kept unless --force.
    """
    _write(config.GLOBAL_SETTINGS_FILE, f"""# jobstudio — machine-level settings (plan §3.6).
#
# The per-shell $JOBSTUDIO_DATA and the per-checkout .jobstudio-data both win over
# this, so a sandbox checkout can point elsewhere without editing this file.
#
# Identity does NOT belong here — that lives in <data-root>/config.yaml and travels
# with the data. This file is for where things are.

[{config.GLOBAL_SECTION}]
{config.GLOBAL_DATA_ROOT_KEY} = {root}

# Optional, all per-machine. Supported platforms are macOS and Linux; setting these
# is also how a platform the toolkit does not know about is made to work.
#
# chrome_path       = /usr/bin/google-chrome     # PDF export; found automatically otherwise
# open_command      = xdg-open                   # "Open folder"; `open` on macOS, `xdg-open` elsewhere
# editor_url_scheme = vscode://file/             # the "Open in VS Code" links
""", force)


# ---------------------------------------------------------------------------
# the database
# ---------------------------------------------------------------------------

def bootstrap_db(root: Path, venv_python: Path, from_example: bool,
                 admin_user: str | None = None, admin_email: str | None = None,
                 skip_admin: bool = False) -> None:
    env = {**os.environ, "JOBSTUDIO_DATA": str(root)}
    manage = REPO / "src" / "web" / "manage.py"

    def run(*args: str) -> None:
        subprocess.run([str(venv_python), str(manage), *args],
                       env=env, check=True, capture_output=True, text=True)

    run("migrate", "--no-input")
    _say("migrated database")

    if from_example:
        # Absolute path on purpose: a bare name would resolve through FIXTURE_DIRS,
        # which points at the example fixture anyway — but being explicit here means
        # this cannot silently load the wrong file if FIXTURE_DIRS ever moves.
        run("loaddata", str(EXAMPLE / "backups" / "django" / "dump.json"))
        _say("loaded   example tracker data")

    run("import_jobs", "--quiet")
    _say("imported areas and base CVs from the data root")

    if not skip_admin:
        ensure_admin(root, venv_python, admin_user, admin_email)


ADMIN_PASSWORD_ENV = "JOBSTUDIO_ADMIN_PASSWORD"
DEFAULT_ADMIN_USER = "admin"
DEFAULT_ADMIN_PASSWORD = "admin"


def ensure_admin(root: Path, venv_python: Path, user: str | None, email: str | None) -> None:
    """Make sure there is a way into the Django admin, or say how to get one.

    Since Phase 6 the admin is the editing surface, so an install with no account
    cannot change anything — and the failure is silent: the app browses fine and only
    the login screen says no. The example fixture deliberately ships no `auth.user`
    (a public repo must not carry a password hash), so a fresh install has none.

    The password comes from $JOBSTUDIO_ADMIN_PASSWORD, never a flag: a flag lands in
    shell history and in the process list.
    """
    env = {**os.environ, "JOBSEARCH_DATA": str(root), "JOBSTUDIO_DATA": str(root)}
    manage = REPO / "src" / "web" / "manage.py"
    count = subprocess.run(
        [str(venv_python), str(manage), "shell", "-c",
         "from django.contrib.auth.models import User; print(User.objects.count())"],
        env=env, capture_output=True, text=True)
    existing = count.stdout.strip().splitlines()[-1] if count.returncode == 0 else "?"

    if existing not in ("0", "?"):
        _say(f"admin account already exists ({existing})")
        return

    # Defaults to admin/admin so a new install can edit immediately. Defensible because
    # the dev server binds 127.0.0.1 and the data is the user's own — but only while it
    # stays local, so the default is announced loudly rather than set quietly.
    chosen_user = user or DEFAULT_ADMIN_USER
    password = os.environ.get(ADMIN_PASSWORD_ENV, "") or DEFAULT_ADMIN_PASSWORD
    is_default = password == DEFAULT_ADMIN_PASSWORD

    subprocess.run(
        [str(venv_python), str(manage), "createsuperuser", "--noinput",
         "--username", chosen_user, "--email", email or f"{chosen_user}@example.com"],
        env={**env, "DJANGO_SUPERUSER_PASSWORD": password}, check=True,
        capture_output=True, text=True)

    if is_default:
        _say(f"created admin account '{chosen_user}' with the DEFAULT PASSWORD "
             f"'{DEFAULT_ADMIN_PASSWORD}'")
        _say("  fine while the server stays on 127.0.0.1. Change it before it does not:")
        _say(f"    tools/py src/web/manage.py changepassword {chosen_user}")
    else:
        _say(f"created admin account '{chosen_user}'")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-root", required=True)
    ap.add_argument("--from-example", action="store_true",
                    help="populate with the fictional example job search")
    ap.add_argument("--name", default="Your Name")
    ap.add_argument("--email", default="you@example.com")
    ap.add_argument("--location", default="")
    ap.add_argument("--venv-python", default=sys.executable,
                    help="interpreter tools/py should exec (default: this one)")
    ap.add_argument("--admin-user", default=None,
                    help=f"username for the Django admin account (default: "
                         f"{DEFAULT_ADMIN_USER!r}); password from "
                         f"${ADMIN_PASSWORD_ENV}, defaulting to "
                         f"{DEFAULT_ADMIN_PASSWORD!r}. There is no --admin-password on "
                         "purpose: a flag lands in shell history and the process list")
    ap.add_argument("--no-admin", action="store_true",
                    help="do not create an admin account at all")
    ap.add_argument("--admin-email", help="email for the admin account")
    ap.add_argument("--skip-global", action="store_true",
                    help="do not write ~/.jobstudio.ini")
    ap.add_argument("--force", action="store_true",
                    help="overwrite files that already exist")
    a = ap.parse_args()

    root = Path(a.data_root).expanduser().resolve()
    # NOT .resolve(): a virtualenv's bin/python is a symlink to the system interpreter,
    # and resolving it hands back the system one — losing the venv's site-packages, so
    # Django is not importable and every manage.py call fails. Absolute, not resolved.
    venv_python = Path(os.path.abspath(Path(a.venv_python).expanduser()))

    print(f"\njobstudio init → {root}\n")
    make_data_root(root, a.from_example, a.force)
    if a.from_example:
        example_cfg = EXAMPLE / "config.yaml"
        if not (root / "config.yaml").exists() or a.force:
            shutil.copy2(example_cfg, root / "config.yaml")
            _say("copied   example config.yaml")
    else:
        write_config_yaml(root, a.name, a.email, a.location, a.force)
    wire_checkout(root, venv_python, a.force)
    if not a.skip_global:
        write_global_settings(root, a.force)
    bootstrap_db(root, venv_python, a.from_example,
                 None if a.no_admin else a.admin_user, a.admin_email,
                 skip_admin=a.no_admin)

    print(f"\nDone. Data root: {root}")
    print("Next: `tools/py src/jobsdb.py status`, or open the web app.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
