# Generated by Django 5.2.17 on 2026-09-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('heading', models.CharField(blank=True, help_text='Section heading in areas.md', max_length=200)),
                ('fit', models.PositiveSmallIntegerField(default=0, help_text='Stars, 0-5')),
                ('description', models.TextField(blank=True, help_text='From the target YAML')),
                ('notes', models.TextField(blank=True, help_text='From areas.md')),
                ('emphasis', models.JSONField(blank=True, default=list)),
                ('key_terms', models.JSONField(blank=True, default=list)),
                ('expand_sections', models.JSONField(blank=True, default=list)),
                ('condense_sections', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('path', models.CharField(help_text='Relative to the repo root', max_length=500, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date', 'path'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True)),
                ('role_target', models.CharField(blank=True, max_length=200)),
                ('fit', models.PositiveSmallIntegerField(default=0, help_text='Stars, 0-5')),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('researching', 'Researching'), ('contacted', 'Contacted'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='watching', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='tracker.category')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(help_text='As written in applications.md', max_length=200)),
                ('role', models.CharField(max_length=300)),
                ('job_url', models.URLField(blank=True, max_length=1000)),
                ('cv_variant_label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('reviewing', 'Reviewing'), ('saved', 'Saved'), ('discarded', 'Discarded'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='saved', max_length=20)),
                ('next_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=300)),
                ('folder', models.CharField(blank=True, help_text="Path relative to the repo root, or '' if no folder yet", max_length=500)),
                ('detail_md', models.TextField(blank=True, help_text="Raw '## Company — Role' block from applications.md")),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tracker.area')),
                ('company', models.ForeignKey(blank=True, help_text='Matched to companies.md where possible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tracker.company')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('path', models.CharField(help_text='Relative to the repo root', max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='tracker.application')),
            ],
            options={
                'ordering': ['-date', 'path'],
                'unique_together': {('application', 'path')},
            },
        ),
    ]
