# Generated by Django 5.2.17 on 2026-09-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['status_order', 'num']},
        ),
        migrations.AddField(
            model_name='application',
            name='status_order',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rank of `status` in STATUS_SORT_ORDER — lets the DB sort the way the TUI does'),
        ),
    ]
