# Generated by Django 5.2.17 on 2026-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_application_options_application_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('watching', 'Watching')], default='watching', help_text="Derived: 'applied' if the company has any application", max_length=20),
        ),
    ]
