# Generated by Django 5.2.17 on 2026-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='summary',
            field=models.TextField(blank=True, help_text='One-line scannable description, shown in list views'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='The full record — shown on the detail page'),
        ),
    ]
