# Generated by Django 5.2.17 on 2026-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_application_summary_alter_application_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='detail_md',
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('watching', 'Watching')], default='watching', help_text="Derived automatically: 'applied' if the company has any application, else 'watching'", max_length=20),
        ),
    ]
