# Generated by Django 5.2.17 on 2026-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_application_detail_md_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('watching', 'Watching')], default='watching', help_text="Derived automatically: 'applied' if the company has an application actually submitted (applied/interviewing/rejected), else 'watching'", max_length=20),
        ),
    ]
