# Generated by Django 5.2.17 on 2026-09-08 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_status', models.CharField(blank=True, help_text='Blank for the first recorded status', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='tracker.application')),
            ],
            options={
                'ordering': ['-changed_at', '-pk'],
            },
        ),
    ]
