# Generated by Django 5.2.17 on 2026-09-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_applicationstatuschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoverLetter',
        ),
    ]
