# Generated by Django 5.2.17 on 2026-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_delete_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fit_cons',
            field=models.TextField(blank=True, help_text='One point per line'),
        ),
        migrations.AddField(
            model_name='application',
            name='fit_level',
            field=models.CharField(blank=True, choices=[('strong', 'Strong match'), ('moderate', 'Moderate match'), ('stretch', 'Stretch'), ('weak', 'Weak match')], help_text='Overall alignment — drives the banner colour', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='fit_pros',
            field=models.TextField(blank=True, help_text='One point per line'),
        ),
        migrations.AddField(
            model_name='application',
            name='fit_unknowns',
            field=models.TextField(blank=True, help_text='One point per line'),
        ),
    ]
