# Generated by Django 5.2.17 on 2026-09-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_application_fit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, help_text='When the company was added to the tracker. Blank for rows that predate this field — only new additions (via jobsdb.py add-company) set it.', null=True),
        ),
    ]
