# Generated by Django 5.2.17 on 2026-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_company_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv_variant_label',
        ),
        migrations.AddField(
            model_name='application',
            name='cv_base',
            field=models.CharField(choices=[('functional', 'Functional'), ('chronological', 'Chronological')], default='functional', help_text='Which base CV this application tailors from', max_length=20),
        ),
    ]
